esphome:
  name: "temp-sensor"

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "asdolikvbaxdtliugb"

captive_portal:
    
sensor:
  - platform: dht
    pin: 2
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 20s